version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: pocketpaldb
      POSTGRES_USER: adminpocketpal
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/docker/dev.dump:/dump/dev.dump
      - ./infrastructure/docker/setup.sh:/docker-entrypoint-initdb.d/initdb.sh
